[FEAT] QUIT command 구현
falconlee236/IRC_Server pull request #28
Opened 2024-07-18 04:20 UTC by falconlee236

# Summary
Quit command를 구현했습니다

# 변경사항
* Quit command를 구현합니다
* server code에 Quit command를 추가합니다
# 참고사항
* Quit conmand는 현재 username이 등록되어야 작동이 가능하게 구현했습니다
* username등록은 user command 입력이후 true로 바꿔야합니다
* 최종적으로 isRegistered가 바뀌는 기능이 추가했는지 댓글로 알려주세요

2024-07-18 17:35 UTC, jiyuneel requested changes
#37 여기에 겹치는 부분 있어서,, 이거 먼저 merge 하고 conflict 해결해주시면 감사하겠습니다..ㅎ

2024-07-18 17:35 UTC, jiyuneel commented on src/commands/quit.cpp
> +    if (!client->isRegistered())
#39 여기에서 `isRegistered` 를 isPassConfirmed 이것처럼 변수로 바꿨어
그리고 register 될때 true로 바꿉닏당

2024-07-18 17:35 UTC, jiyuneel commented on src/commands/quit.cpp
> +        Server::removeClient(client->getSocket());
Server:: 이거 안붙여도 될듯?!

2024-07-19 05:16 UTC, falconlee236 commented
> #39 여기에 겹치는 부분 있어서,, 이거 먼저 merge 하고 conflict 해결해주시면 감사하겠습니다..ㅎ

수정 완료했습니당

2024-07-19 05:18 UTC, jiyuneel approved these changes
확인확인!!

2024-07-19 05:18 UTC, merged